import { useEffect, useRef, useState } from "react";

function PlusMark({ premium }) { return <span className={`ff-plus-mark ${premium ? "is-active" : ""}`}>{premium ? "+" : ""}</span>; }

export default function Header({ user, settings, onAddTask, onLogout, onPremium }) {
  const [open, setOpen] = useState(false); const ref = useRef(null); const premium = Boolean(settings?.premiumUnlocked);
  useEffect(() => { const close = e => { if (!ref.current?.contains(e.target)) setOpen(false); }; const esc = e => e.key === "Escape" && setOpen(false); document.addEventListener("mousedown",close); document.addEventListener("keydown",esc); return () => { document.removeEventListener("mousedown",close); document.removeEventListener("keydown",esc); }; }, []);
  return <header className="sticky top-0 z-40 flex h-[72px] items-center justify-between border-b border-[var(--ff-border)] bg-[var(--ff-bg)]/85 px-4 backdrop-blur-xl sm:px-6 lg:px-8">
    <div className="flex items-center gap-3 lg:hidden"><div className="ff-mini-logo">F<PlusMark premium={premium}/></div><div><div className="text-sm font-black">FocusFlow</div><div className="text-[8px] font-bold uppercase tracking-[.16em] text-[var(--ff-text-soft)]">{premium ? "Plus" : "Productivity OS"}</div></div></div>
    <div className="hidden lg:block"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[var(--ff-text-soft)]">Workspace</p><h2 className="mt-1 text-sm font-extrabold">Make today count.</h2></div>
    <div className="flex items-center gap-2 sm:gap-3"><button onClick={onAddTask} className="ff-button-primary min-h-10 px-4 text-[11px] font-extrabold">+ <span className="hidden sm:inline">New task</span><span className="sm:hidden">Task</span></button><div className="relative" ref={ref}><button onClick={() => setOpen(v=>!v)} className="flex min-h-10 items-center gap-2 rounded-full border border-[var(--ff-border)] bg-[var(--ff-surface)] px-2.5 shadow-[var(--ff-shadow-soft)]"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[var(--ff-primary)] text-[10px] font-black">{user?.name?.slice(0,1)?.toUpperCase() || "F"}</span><span className="hidden max-w-24 truncate text-[10px] font-bold sm:block">{user?.name}</span><span className="text-[10px] text-[var(--ff-text-soft)]">⌄</span></button>{open && <div className="ff-dropdown absolute right-0 mt-2 w-56 rounded-2xl border border-[var(--ff-border)] bg-[var(--ff-surface)] p-2 shadow-[var(--ff-shadow-3d)]"><div className="border-b border-[var(--ff-border)] px-3 py-2"><p className="text-xs font-black">{premium ? "FocusFlow Plus" : "FocusFlow"}</p><p className="mt-0.5 truncate text-[9px] text-[var(--ff-text-soft)]">{user?.email}</p></div>{!premium && <button className="ff-menu-item" onClick={() => {setOpen(false); onPremium?.();}}>✦ Explore Premium</button>}<button className="ff-menu-item" onClick={() => {setOpen(false); window.dispatchEvent(new CustomEvent("focusflow-open-task"));}}>＋ New Task</button><button className="ff-menu-item danger" onClick={() => {setOpen(false); onLogout?.();}}>↪ Sign out</button></div>}</div></div>
  </header>;
}
